Examples module header
SSRQ-SDS-FDS/ssrq-schema pull request #134
Opened 2023-08-15 11:49 UTC by ChristianSonderUniSG

# Pull request

## Proposed changes

## Types of changes

- [x] New feature (non-breaking change which adds functionality).
- [ ] Enhancement (non-breaking change which enhances functionality)
- [ ] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [ ] I have read the **[README](./README.md)** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-08-15 16:21 UTC, Bpolitycki commented on src/schema/examples/availability.xml
The example is not used anywhere and the example `xml:id` should not be direct party of the example snippet.

2023-08-15 16:25 UTC, Bpolitycki commented on src/schema/examples/availability.xml
The example id should not be part of the example snippet itself.

2023-08-15 16:26 UTC, Bpolitycki commented on src/schema/examples/seriesStmt.xml
May be valid ... but it would be better to use real UUID here.

2023-08-15 16:27 UTC, Bpolitycki requested changes
Use a real UUID in `<seriesStmt/>`...

2023-08-17 07:28 UTC, ChristianSonderUniSG commented on src/schema/examples/seriesStmt.xml
Done

2023-08-17 12:11 UTC, Bpolitycki approved these changes

2023-08-17 12:11 UTC, merged